language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

cache:
  directories:
    - vendor

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:~1.2"
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/codecept run --coverage --coverage-xml "tests/_output/coverage.xml"

after_script:
  - travis_retry wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.xml
